spring:
  profiles:
    active: dev
server:
  servlet:
    context-path: /waiting_room

waiting-room:
  default-algorithm-type: FIFO
  default-work-mode: MORNING
  default-capacity: 15

visit:
  default-visitor-status: WAITING
  default-priority: 100
  default-estimated-processing-time: 10m
